// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillMatrix.Api.Data;

#nullable disable

namespace SkillMatrix.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927142347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillMatrix.Api.Models.Area", b =>
                {
                    b.Property<string>("AreaCode")
                        .HasColumnType("text");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AreaCode");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.AssignEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("A")
                        .HasColumnType("boolean");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("C")
                        .HasColumnType("boolean");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("T")
                        .HasColumnType("boolean");

                    b.Property<bool>("U")
                        .HasColumnType("boolean");

                    b.Property<string>("WorkStationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaCode");

                    b.HasIndex("EmpId");

                    b.HasIndex("WorkStationCode");

                    b.ToTable("AssignEmployees");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.Contractor", b =>
                {
                    b.Property<string>("ContractorId")
                        .HasColumnType("text");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractorPhoto")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContractorId");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.Department", b =>
                {
                    b.Property<string>("DeptCode")
                        .HasColumnType("text");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeptCode");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.Eaton", b =>
                {
                    b.Property<string>("EatonId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EatonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.HasKey("EatonId");

                    b.ToTable("Eatons");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.Employee", b =>
                {
                    b.Property<string>("EmpId")
                        .HasColumnType("text");

                    b.Property<string>("DeptCode")
                        .HasColumnType("text");

                    b.Property<string>("EmpCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.HasKey("EmpId");

                    b.HasIndex("DeptCode");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeptCode");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.WorkStation", b =>
                {
                    b.Property<string>("WorkStationCode")
                        .HasColumnType("text");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkStationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkStationCode");

                    b.HasIndex("AreaCode");

                    b.ToTable("WorkStations");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.AssignEmployee", b =>
                {
                    b.HasOne("SkillMatrix.Api.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillMatrix.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillMatrix.Api.Models.WorkStation", "WorkStation")
                        .WithMany()
                        .HasForeignKey("WorkStationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Employee");

                    b.Navigation("WorkStation");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.Employee", b =>
                {
                    b.HasOne("SkillMatrix.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.User", b =>
                {
                    b.HasOne("SkillMatrix.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SkillMatrix.Api.Models.WorkStation", b =>
                {
                    b.HasOne("SkillMatrix.Api.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });
#pragma warning restore 612, 618
        }
    }
}
